# Generated by Django 5.0.14 on 2026-09-16 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('herb_type', models.CharField(choices=[('herb', 'Herb'), ('spice', 'Spice')], max_length=20)),
                ('variety', models.CharField(blank=True, max_length=100, null=True)),
                ('part_used', models.CharField(choices=[('leaf', 'Leaf'), ('root', 'Root'), ('stem', 'Stem'), ('flower', 'Flower'), ('seed', 'Seed'), ('bark', 'Bark'), ('whole_plant', 'Whole Plant')], max_length=20)),
                ('use_category', models.CharField(choices=[('culinary', 'Culinary'), ('medicinal', 'Medicinal'), ('commercial', 'Commercial'), ('multiple', 'Multiple Uses')], max_length=20)),
                ('preparation_notes', models.TextField(blank=True, null=True)),
                ('drying_method', models.CharField(choices=[('air_dry', 'Air Dried'), ('sun_dry', 'Sun Dried'), ('oven_dry', 'Oven Dried'), ('fresh_only', 'Used Fresh Only'), ('none', 'Not Dried')], default='none', max_length=20)),
                ('harvest_type', models.CharField(choices=[('one_time', 'One-time Harvest'), ('recurring', 'Recurring Harvest')], default='recurring', max_length=20)),
                ('plot_bed', models.CharField(max_length=100)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planted', 'Planted'), ('growing', 'Growing'), ('active', 'Active (recurring harvest)'), ('harvested', 'Harvested'), ('dormant', 'Dormant'), ('retired', 'Retired')], default='planted', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='herb_photos/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herbs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-planting_date'],
            },
        ),
        migrations.CreateModel(
            name='HerbHarvestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('pieces', 'Pieces (count)'), ('bunches', 'Bunches')], default='kg', max_length=10)),
                ('part_harvested', models.CharField(blank=True, choices=[('leaf', 'Leaf'), ('root', 'Root'), ('stem', 'Stem'), ('flower', 'Flower'), ('seed', 'Seed'), ('bark', 'Bark'), ('whole_plant', 'Whole Plant')], max_length=20, null=True)),
                ('drying_method', models.CharField(blank=True, choices=[('air_dry', 'Air Dried'), ('sun_dry', 'Sun Dried'), ('oven_dry', 'Oven Dried'), ('fresh_only', 'Used Fresh Only'), ('none', 'Not Dried')], max_length=20, null=True)),
                ('plot_bed', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_logs', to='herbs.herb')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herb_harvest_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-harvest_date'],
            },
        ),
    ]
