# Generated by Django 5.0.14 on 2026-08-15 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=20, unique=True)),
                ('breed', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('boar', 'Boar'), ('sow', 'Sow'), ('gilt', 'Gilt'), ('barrow', 'Barrow')], max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('deceased', 'Deceased')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tag_id'],
            },
        ),
        migrations.CreateModel(
            name='FeedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(max_length=200)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('required_by_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PigActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pig_reference', models.CharField(max_length=50)),
                ('report_date', models.DateField()),
                ('activity_type', models.CharField(choices=[('observation', 'Observation'), ('health_concern', 'Health Concern'), ('weight_recorded', 'Weight Recorded'), ('farrowing', 'Farrowing'), ('death', 'Death')], max_length=20)),
                ('details', models.TextField()),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pig_activity_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='PigSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('buyer_name', models.CharField(max_length=200)),
                ('weight_at_sale_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='pigs.pig')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pig_sales_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='PigVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200)),
                ('date_given', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('administered_by', models.CharField(blank=True, max_length=200, null=True)),
                ('pig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='pigs.pig')),
            ],
            options={
                'ordering': ['-date_given'],
            },
        ),
        migrations.CreateModel(
            name='PigWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weigh_date', models.DateField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='pigs.pig')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pig_weights_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-weigh_date'],
            },
        ),
    ]
