# Generated by Django 5.0.14 on 2026-08-15 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_line', models.CharField(choices=[('nettle_processing', 'Stinging Nettle Processing'), ('soya_intake', 'Soya Bean Intake'), ('dried_vegetables', 'Dried Vegetables Production'), ('soya_oil_flour', 'Soya Oil & Flour Processing')], max_length=30)),
                ('log_date', models.DateField()),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('input_description', models.CharField(blank=True, max_length=300, null=True)),
                ('input_quantity_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('output_description', models.CharField(blank=True, max_length=300, null=True)),
                ('output_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('output_unit', models.CharField(choices=[('kg', 'Kilograms'), ('litres', 'Litres'), ('units', 'Units')], default='kg', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-log_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=300)),
                ('quantity_description', models.CharField(max_length=200)),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_orders_approved', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
