# Generated by Django 5.0.14 on 2026-09-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_produce_report_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='crop_type',
            field=models.CharField(choices=[('vegetable', 'Vegetable'), ('root', 'Root'), ('fruit', 'Fruit')], max_length=20),
        ),
    ]
