# Generated by Django 5.0.14 on 2026-08-15 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
                ('stocking_date', models.DateField(blank=True, null=True)),
                ('stocking_count', models.PositiveIntegerField(blank=True, null=True)),
                ('feed_type', models.CharField(blank=True, max_length=200, null=True)),
                ('target_harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('fingerlings', 'Fingerlings'), ('harvest_ready', 'Harvest Ready'), ('harvested', 'Harvested'), ('empty', 'Empty')], default='empty', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PondReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('activity_type', models.CharField(choices=[('feed_log', 'Feed Log'), ('water_quality', 'Water Quality'), ('weight_sample', 'Weight Sample'), ('mortality', 'Mortality'), ('harvest', 'Harvest')], max_length=20)),
                ('quantity_value', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='aquaculture.pond')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pond_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
    ]
