# Generated by Django 5.0.14 on 2026-08-16 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoultryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('chicken', 'Chicken'), ('goose', 'Goose'), ('duck', 'Duck'), ('turkey', 'Turkey'), ('other', 'Other')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('mixed', 'Mixed')], default='mixed', max_length=10)),
                ('count', models.PositiveIntegerField()),
                ('average_size_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_layer', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('deceased', 'Deceased')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poultry_batches_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['species', 'batch_name'],
            },
        ),
        migrations.CreateModel(
            name='PoultryActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('activity_type', models.CharField(choices=[('observation', 'Observation'), ('health_concern', 'Health Concern'), ('mortality', 'Mortality'), ('hatching', 'Hatching')], max_length=20)),
                ('count_affected', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.TextField()),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poultry_activity_reports', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_reports', to='poultry.poultrybatch')),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='EggCollectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField()),
                ('eggs_collected', models.PositiveIntegerField()),
                ('broken_eggs', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egg_logs_recorded', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_logs', to='poultry.poultrybatch')),
            ],
            options={
                'ordering': ['-collection_date'],
            },
        ),
        migrations.CreateModel(
            name='PoultryFeedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_date', models.DateField()),
                ('feed_type', models.CharField(max_length=200)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_logs', to='poultry.poultrybatch')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poultry_feed_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-feed_date'],
            },
        ),
    ]
